services:
  web:
    build: .
    deploy:
      resources:
        limits:
          cpus: '4.0'   # Ограничение использования до 4 CPU
        reservations:
          cpus: '4.0'   # Резервирует 4 CPU для работы
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: myproject.settings
     
    env_file:
      - .env

  db:
    image: postgres:13
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: PythonTestDB

volumes:
  postgres_data:
