# Generated by Django 4.1 on 2024-11-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_delete_article_news_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="cr_avtor",
            field=models.CharField(default="Incognito", max_length=200),
        ),
        migrations.AlterField(
            model_name="news",
            name="content",
            field=models.TextField(max_length=50),
        ),
    ]
