# Generated by Django 4.1 on 2024-11-18 11:14

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_cr_avtor_alter_news_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='news',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='news_news_search__87782f_gin'),
        ),
    ]
